spring.application.name=api-gateway
server.port = 8084

#Eureka Configs
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true

#Zipkin
management.tracing.sampling.probability = 1.0

#Gateway Config
spring.cloud.gateway.server.webmvc.routes[0].id = company-service
spring.cloud.gateway.server.webmvc.routes[0].uri = lb://COMPANY-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/company/**

spring.cloud.gateway.server.webmvc.routes[1].id = job-service
spring.cloud.gateway.server.webmvc.routes[1].uri = lb://JOB-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.server.webmvc.routes[2].id = review-service
spring.cloud.gateway.server.webmvc.routes[2].uri = lb://REVIEW-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/reviews/**

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

#Config Server
spring.config.import = optional:configserver:http://localhost:8888
