spring.application.name=company-service

#Config Server
spring.config.import = optional:configserver:http://localhost:8888

#server.port = 8085

# H2 Database Configs
#spring.h2.console.enabled=true
#spring.datasource.url = jdbc:h2:mem:test
#spring.datasource.username=sa
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update

# Postgres Configs
#spring.datasource.url=jdbc:postgresql://localhost:5432/hirehub_company
#spring.datasource.username = charlie
#spring.datasource.password = root
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = create-drop

#Eureka
#eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
#eureka.client.register-with-eureka = true
#eureka.client.fetch-registry = true

#Zipkin
#management.tracing.sampling.probability = 1.0

# Resilience4J
resilience4j.ratelimiter.rateLimiterAspectOrder=0
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2

## Resilience4J JOB-SERVICE
resilience4j.retry.instances.jobRetry.max-attempts=3
resilience4j.retry.instances.jobRetry.wait-duration=500ms
resilience4j.retry.instances.jobRetry.ignore-exceptions=feign.FeignException$NotFound

resilience4j.circuitbreaker.instances.jobBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.jobBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.jobBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.jobBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.jobBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.jobBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.jobBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.jobBreaker.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.jobBreaker.ignore-exceptions=feign.FeignException$NotFound

#Resilience4J RateLimiter for OUR COMPANY-SERVICE
resilience4j.ratelimiter.instances.writeCompanyRateLimiter.timeout-duration=0s
resilience4j.ratelimiter.instances.writeCompanyRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.writeCompanyRateLimiter.limit-for-period=5

resilience4j.ratelimiter.instances.readCompanyRateLimiter.timeout-duration=0s
resilience4j.ratelimiter.instances.readCompanyRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.readCompanyRateLimiter.limit-for-period=20