spring.application.name=hirehub-job-service

server.port = 8086

# H2 Database Configs
#spring.h2.console.enabled=true
#spring.datasource.url = jdbc:h2:mem:test
#spring.datasource.username=sa
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update

# Postgres Configs
spring.datasource.url=jdbc:postgresql://localhost:5432/hirehub_job
spring.datasource.username = charlie
spring.datasource.password = root
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create-drop