spring.application.name=job-service

#Config Server
spring.config.import = optional:configserver:http://localhost:8888

#Actuator
management.endpoints.web.exposure.include = health
management.endpoint.health.show-details = always
management.health.circuitbreakers.enabled = true

#server.port = 8086

# H2 Database Configs
#spring.h2.console.enabled=true
#spring.datasource.url = jdbc:h2:mem:test
#spring.datasource.username=sa
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update

# Postgres Configs
#spring.datasource.url=jdbc:postgresql://localhost:5432/hirehub_job
#spring.datasource.username = charlie
#spring.datasource.password = root
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = create-drop

#Eureka Configs
#eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
#eureka.client.register-with-eureka = true
#eureka.client.fetch-registry = true

#Zipkin
#management.tracing.sampling.probability = 1.0

## Resilience4J
#resilience4j.ratelimiter.rateLimiterAspectOrder=0
#resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
#resilience4j.retry.retryAspectOrder=2
#
## Resilience4J COMPANY-SERVICE
#resilience4j.ratelimiter.instances.companyRateLimiter.timeout-duration=0s
#resilience4j.ratelimiter.instances.companyRateLimiter.limit-refresh-period=1s
#resilience4j.ratelimiter.instances.companyRateLimiter.limit-for-period=20
#
#resilience4j.retry.instances.companyRetry.max-attempts=3
#resilience4j.retry.instances.companyRetry.wait-duration=500ms
#resilience4j.retry.instances.companyRetry.ignore-exceptions=feign.FeignException$NotFound
#
#resilience4j.circuitbreaker.instances.companyBreaker.slidingWindowSize=10
#resilience4j.circuitbreaker.instances.companyBreaker.minimumNumberOfCalls=5
#resilience4j.circuitbreaker.instances.companyBreaker.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.companyBreaker.waitDurationInOpenState=10s
#resilience4j.circuitbreaker.instances.companyBreaker.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.companyBreaker.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.companyBreaker.automatic-transition-from-open-to-half-open-enabled=true
#resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-type=count_based
#resilience4j.circuitbreaker.instances.companyBreaker.ignore-exceptions=feign.FeignException$NotFound
#
#
## Resilience4J REVIEW-SERVICE
#resilience4j.retry.instances.reviewRetry.max-attempts=3
#resilience4j.retry.instances.reviewRetry.wait-duration=500ms
#resilience4j.retry.instances.reviewRetry.ignore-exceptions=feign.FeignException$NotFound
#
#resilience4j.circuitbreaker.instances.reviewBreaker.slidingWindowSize=10
#resilience4j.circuitbreaker.instances.reviewBreaker.minimumNumberOfCalls=5
#resilience4j.circuitbreaker.instances.reviewBreaker.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.reviewBreaker.waitDurationInOpenState=10s
#resilience4j.circuitbreaker.instances.reviewBreaker.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.reviewBreaker.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.reviewBreaker.automatic-transition-from-open-to-half-open-enabled=true
#resilience4j.circuitbreaker.instances.reviewBreaker.sliding-window-type=count_based
#resilience4j.circuitbreaker.instances.reviewBreaker.ignore-exceptions=feign.FeignException$NotFound
#
## Resilience4J JOB-SERVICE
#resilience4j.ratelimiter.instances.writeJobRateLimiter.timeout-duration=0s
#resilience4j.ratelimiter.instances.writeJobRateLimiter.limit-refresh-period=1s
#resilience4j.ratelimiter.instances.writeJobRateLimiter.limit-for-period=5
#
#resilience4j.ratelimiter.instances.readJobRateLimiter.timeout-duration=0s
#resilience4j.ratelimiter.instances.readJobRateLimiter.limit-refresh-period=1s
#resilience4j.ratelimiter.instances.readJobRateLimiter.limit-for-period=20
